local M = {}

local colors = require("arrakis-night.palette")

M.setup = function()
  return {
    Normal = { fg = colors.fg, bg = colors.bg, },
    NormalFloat = { fg = colors.fg, bg = colors.bg, },
    Comment = { fg = colors.comment, },
    Constant = { fg = colors.yellow, },
    String = { fg = colors.green, },
    Character = { fg = colors.green, },
    Number = { fg = colors.yellow, },
    Boolean = { fg = colors.yellow, },
    Float = { fg = colors.yellow, },
    FloatBorder = { fg = colors.white, },
    Operator = { fg = colors.cyan, },
    Keyword = { fg = colors.red, },
    Keywords = { fg = colors.red, },
    Identifier = { fg = colors.fg, },
    Function = { fg = colors.blue, },
    Statement = { fg = colors.red, },
    Conditional = { fg = colors.red, },
    Repeat = { fg = colors.red, },
    Label = { fg = colors.yellow, },
    Exception = { fg = colors.red, },
    PreProc = { fg = colors.yellow, },
    Include = { fg = colors.red, },
    Define = { fg = colors.red, },
    Title = { fg = colors.blue, },
    Macro = { fg = colors.red, },
    PreCondit = { fg = colors.cyan, },
    Type = { fg = colors.red, },
    StorageClass = { fg = colors.red, },
    Structure = { fg = colors.red, },
    TypeDef = { fg = colors.red, },
    Special = { fg = colors.red },
    SpecialComment = { fg = colors.comment, },
    Error = { fg = colors.error, undercurl = true, },
    Todo = { fg = colors.orange, bold = true },
    Underlined = { fg = colors.blue, underline = true, },

    Cursor = { reverse = true, },
    CursorLineNr = { fg = colors.fg, bold = true, },

    SignColumn = { bg = colors.bg, },

    Conceal = { fg = colors.comment, },
    CursorColumn = { bg = colors.black, },
    CursorLine = { bg = colors.selection, },
    ColorColumn = { bg = colors.selection, },

    StatusLine = { fg = colors.white, bg = colors.selection, },
    StatusLineNC = { fg = colors.comment, },
    StatusLineTerm = { fg = colors.white, bg = colors.black, },
    StatusLineTermNC = { fg = colors.comment, },

    Directory = { fg = colors.blue, },
    DiffAdd = { fg = colors.bg, bg = colors.green, },
    DiffChange = { fg = colors.orange, },
    DiffDelete = { fg = colors.red, },
    DiffText = { fg = colors.comment, },

    ErrorMsg = { fg = colors.error, },
    VertSplit = { fg = colors.black, },
    WinSeparator = { fg = colors.black, },
    Folded = { fg = colors.comment, },
    FoldColumn = {},
    Search = { fg = colors.black, bg = colors.search },
    IncSearch = { fg = colors.black, bg = colors.search },
    LineNr = { fg = colors.comment, },
    MatchParen = { fg = colors.match, underline = true, },
    NonText = { fg = colors.nontext, },
    Pmenu = { fg = colors.white, bg = colors.menu, },
    PmenuSel = { fg = colors.white, bg = colors.selection, },
    PmenuSbar = { bg = colors.bg, },
    PmenuThumb = { bg = colors.selection, },

    Question = { fg = colors.red, },
    QuickFixLine = { fg = colors.orange, },
    SpecialKey = { fg = colors.nontext, },

    SpellBad = { fg = colors.error, underline = true, },
    SpellCap = { fg = colors.orange, },
    SpellLocal = { fg = colors.orange, },
    SpellRare = { fg = colors.orange, },

    TabLine = { fg = colors.comment, },
    TabLineSel = { fg = colors.white, },
    TabLineFill = { bg = colors.bg, },
    Terminal = { fg = colors.white, bg = colors.black, },
    Visual = { bg = colors.visual, },
    VisualNOS = { fg = colors.visual, },
    WarningMsg = { fg = colors.yellow, },
    WildMenu = { fg = colors.black, bg = colors.white, },

    EndOfBuffer = endOfBuffer,

    -- TreeSitter
    ['@error'] = { fg = colors.error, },
    ['@string'] = { fg = colors.green, },
    ['@string.escape'] = { fg = colors.cyan, },
    ['@string.special.symbol'] = { fg = colors.red, },
    ['@string.regexp'] = { fg = colors.red, },
    ['@character'] = { fg = colors.green, },
    ['@number'] = { fg = colors.yellow, },
    ['@boolean'] = { fg = colors.yellow, },
    ['@number.float'] = { fg = colors.yellow, },
    ['@annotation'] = { fg = colors.yellow, },
    ['@attribute'] = { fg = colors.cyan, },
    ['@module'] = { fg = colors.green, },
    ['@property'] = { fg = colors.fg, },
    ['@constructor'] = { fg = colors.blue, },
    ['@structure'] = { fg = colors.red, },
    ['@operator'] = { fg = colors.cyan, },
    ['@label'] = { fg = colors.yellow, },

    ['@punctuation.delimiter'] = { fg = colors.fg, },
    ['@punctuation.bracket'] = { fg = colors.fg, },

    ['@constant'] = { fg = colors.fg, },
    ['@constant.builtin'] = { fg = colors.red, },
    ['@constant.macro'] = { fg = colors.orange, },

    ['@function'] = { fg = colors.blue, },
    ['@function.builtin'] = { fg = colors.red, },
    ['@function.macro'] = { fg = colors.orange, },
    ['@function.method'] = { fg = colors.blue, },

    ['@keyword'] = { fg = colors.red, },
    ['@keyword.return'] = { fg = colors.red, },
    ['@keyword.function'] = { fg = colors.red, },
    ['@keyword.operator'] = { fg = colors.red, },
    ['@keyword.conditional'] = { fg = colors.red, },
    ['@keyword.conditional.ternary'] = { fg = colors.cyan, },
    ['@keyword.repeat'] = { fg = colors.red, },
    ['@keyword.exception'] = { fg = colors.red, },
    ['@keyword.include'] = { fg = colors.red, },
    ['@keyword.directive'] = { fg = colors.nontext, },
    ['@keyword.directive.define'] = { fg = colors.red, },

    ['@type'] = { fg = colors.fg, },
    ['@type.builtin'] = { fg = colors.red, },
    ['@type.definition'] = { fg = colors.orange, },
    ['@type.qualifier'] = { fg = colors.green, },

    ['@variable'] = { fg = colors.fg, },
    ['@variable.builtin'] = { fg = colors.red, },
    ['@variable.parameter'] = { fg = colors.fg, },
    ['@variable.parameter.reference'] = { fg = colors.fg, },
    ['@variable.member'] = { fg = colors.fg, },

    ['@markup'] = { fg = colors.red, },
    ['@markup.strong'] = { fg = colors.blue, bold = true, },     -- bold
    ['@markup.emphasis'] = { fg = colors.orange, italic = true, }, -- italic
    ['@markup.italic'] = { fg = colors.blue, italic = true, }, -- italic
    ['@markup.underline'] = { fg = colors.blue, underline = true, },
    ['@markup.heading'] = { fg = colors.red, bold = true, },        -- title
    ['@markup.raw'] = { fg = colors.yellow, },                 -- inline code
    ['@markup.link.url'] = { fg = colors.nontext, italic = true, },      -- urls
    ['@markup.link'] = { fg = colors.blue, bold = true, },
    ['@markup.link.label.symbol'] = { fg = colors.yellow, },
    ['@markup.list'] = { fg = colors.red, },

    ['@tag'] = { fg = colors.cyan, },
    ['@tag.attribute'] = { fg = colors.green, },
    ['@tag.delimiter'] = { fg = colors.cyan, },

    -- Semantic
    ['@class'] = { fg = colors.red },
    ['@struct'] = { fg = colors.red },
    ['@enum'] = { fg = colors.red },
    ['@enumMember'] = { fg = colors.orange },
    ['@event'] = { fg = colors.red },
    ['@interface'] = { fg = colors.red },
    ['@modifier'] = { fg = colors.red },
    ['@regexp'] = { fg = colors.green },
    ['@typeParameter'] = { fg = colors.cyan },
    ['@decorator'] = { fg = colors.cyan },

    -- LSP Semantic (0.9+)
    ['@lsp.type.class'] = { fg = colors.orange },
    ['@lsp.type.enum'] = { fg = colors.orange },
    ['@lsp.type.decorator'] = { fg = colors.cyan },
    ['@lsp.type.enumMember'] = { fg = colors.fg },
    ['@lsp.type.function'] = { fg = colors.blue, },
    ['@lsp.type.interface'] = { fg = colors.red },
    ['@lsp.type.macro'] = { fg = colors.red },
    ['@lsp.type.method'] = { fg = colors.blue, },
    ['@lsp.type.namespace'] = { fg = colors.green, },
    ['@lsp.type.parameter'] = { fg = colors.fg, },
    ['@lsp.type.property'] = { fg = colors.fg, },
    ['@lsp.type.struct'] = { fg = colors.red },
    ['@lsp.type.type'] = { fg = colors.red, },
    ['@lsp.type.variable'] = { fg = colors.fg, },

    -- LSP
    DiagnosticError = { fg = colors.error, },
    DiagnosticWarn = { fg = colors.orange, },
    DiagnosticInfo = { fg = colors.fg, },
    DiagnosticHint = { fg = colors.blue, },
    DiagnosticUnderlineError = { undercurl = true, sp = colors.error, },
    DiagnosticUnderlineWarn = { undercurl = true, sp = colors.orange, },
    DiagnosticUnderlineInfo = { undercurl = true, sp = colors.fg, },
    DiagnosticUnderlineHint = { undercurl = true, sp = colors.blue, },
    DiagnosticSignError = { fg = colors.error, },
    DiagnosticSignWarn = { fg = colors.orange, },
    DiagnosticSignInfo = { fg = colors.fg, },
    DiagnosticSignHint = { fg = colors.blue, },
    DiagnosticFloatingError = { fg = colors.error, },
    DiagnosticFloatingWarn = { fg = colors.orange, },
    DiagnosticFloatingInfo = { fg = colors.fg, },
    DiagnosticFloatingHint = { fg = colors.blue, },
    DiagnosticVirtualTextError = { fg = colors.red, },
    DiagnosticVirtualTextWarn = { fg = colors.orange, },
    DiagnosticVirtualTextInfo = { fg = colors.fg, },
    DiagnosticVirtualTextHint = { fg = colors.blue, },

    LspDiagnosticsDefaultError = { fg = colors.error, },
    LspDiagnosticsDefaultWarning = { fg = colors.orange, },
    LspDiagnosticsDefaultInformation = { fg = colors.fg, },
    LspDiagnosticsDefaultHint = { fg = colors.blue, },
    LspDiagnosticsUnderlineError = { fg = colors.error, undercurl = true, },
    LspDiagnosticsUnderlineWarning = { fg = colors.orange, undercurl = true, },
    LspDiagnosticsUnderlineInformation = { fg = colors.fg, undercurl = true, },
    LspDiagnosticsUnderlineHint = { fg = colors.blue, undercurl = true, },
    LspReferenceText = { fg = colors.orange, },
    LspReferenceRead = { fg = colors.orange, },
    LspReferenceWrite = { fg = colors.orange, },
    LspCodeLens = { fg = colors.cyan, },
    LspInlayHint = { fg = colors.nontext, },
  }
end

return M
